### PR TITLE
Add PHP 8.2

### PR DESCRIPTION
**Pull request by kaszarobert**
I created the 8.2 option and Dockerfiles for apache/fpm images 8.2 based on 8.1 images. Please review.

### CODE REVIEW

**Comment by chrillep** [comment]
@pirog ping

**Comment by rabauss** [comment]
This PR could also declare all PHP 7 as legacy!

**Comment by agentphoenix** [comment]
Any chance of getting this released soon? We're in need of testing on PHP 8.2 that's been released for a month now.

**Comment by reynoldsalec** [comment]
Checking this out now, thanks @kaszarobert for the PR!

**Comment by reynoldsalec** [comment]
Moving the party over to #51; should be merging shortly.

**Comment by reynoldsalec** [comment]
FYI, #51 is merged in this plugin as release `v0.7.1` and will be included in Lando release `v3.9.0`; prior to that being released you can custom install the updated PHP plugin via the instructions [here](https://docs.lando.dev/php/#custom-installation).

Thanks again @kaszarobert for getting us moving on this; if you're looking for another chance to contribute, the same type of process needs to be performed for some of the service provider plugins (ex: [@lando/pantheon](https://github.com/lando/pantheon)).

**Comment by klonos** [comment]
> ...prior to that being released you can custom install the updated PHP plugin via the instructions [here](https://docs.lando.dev/php/#custom-installation).

@reynoldsalec I've tried running this on my Mac:

```
docker run --rm -it -v ${HOME}/.lando/plugins:/plugins -w /tmp node:14-alpine sh -c \
  "yarn init -y \
  && yarn add @lando/php@0.7.1 --production --flat --no-default-rc --no-lockfile --link-duplicates \
  && yarn install --production --cwd /tmp/node_modules/@lando/php \
  && mkdir -p /plugins/@lando \
  && mv --force /tmp/node_modules/@lando/php /plugins/@lando/php"
```

...but got this:
```
yarn global v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
warning "lando@0.0.1" has no binaries
Done in 2.08s.
yarn init v1.22.19
warning The yes flag has been set. This will automatically answer yes to all questions, which may have security implications.
success Saved package.json
Done in 0.05s.
yarn add v1.22.19
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
error @lando/php@0.7.1: The engine "node" is incompatible with this module. Expected version ">=16.0.0". Got "14.21.2"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

I then also tried adding `yarn global add lando/php --ignore-engines` to the mix, but that didn't get me very far either:
```
yarn global v1.22.19
[1/4] Resolving packages...
error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```

I'm new to this, and all I want is to be able to spin up lando instances with php 8.2. I don't know how to troubleshoot any of that. Any pointers?

**Comment by reynoldsalec** [comment]
@klonos I'm late to the party here but I believe changing `node:14-alpine` to `node:16-alpine` in the `docker run` would fix your original issue. We should update the documentation to reflect that; this plugin (and possibly others) have been updated to node 16 apparently :)

That said, Lando 3.9.0 now includes this: https://github.com/lando/lando/releases/tag/v3.9.0, so downloading that might be the easiest solution.

**Comment by reynoldsalec** [comment]
...confirmed that was the issue and update the docs, I think this needs to be done across all Lando plugins. Time to break out my bulk updating script!

**Pull request closed without merging**
