### PR TITLE
Update php support according to https://www.php.net/supported-version…

### PR DESCRIPTION
**Pull request by tvlooy**
…s.php

### Bare minimum self-checks

> [What do you think of a person who only does the bare minimum?](https://getyarn.io/yarn-clip/dcf80710-425e-478b-bde1-c107bd11e849)

- [x] I've updated this PR with the latest code from `main`
- [x] I've done a cursory QA pass of my code locally
- [x] I've ensured all automated status check and tests pass
- [ ] I've [connected this PR to an issue](https://help.zenhub.com/support/solutions/articles/43000010350-connecting-pull-requests-to-github-issues)

### Pieces of flare

- [ ] I've written a unit or functional test for my code
- [x] I've updated relevant documentation it my code changes it
- [x] I've updated this repo's README if my code changes it
- [x] I've updated this repo's CHANGELOG with my change unless its a trivial change (like updating a typo in the docs)

### Finally

- [ ] I've [requested a review](https://help.github.com/en/articles/requesting-a-pull-request-review) with relevant people

If you have any issues or need help please join the `#contributors` channel in the [Lando slack](https://www.launchpass.com/devwithlando) and someone will gladly help you out!

You can also check out the [coder guide](https://docs.lando.dev/contrib/coder.html).

### CODE REVIEW

**Comment by reynoldsalec** [comment]
So I hate this, but the big issue with the way Lando v3 services handle the "default" version is this: if we update the default version, next time people rebuild their apps, they'll get a dramatically different version of PHP. There is a fairly large number of users who are relying on the "default" setting, and changing it from underneath them will probably be problematic.

This is a big reason @pirog is planning on eliminating default versions in v4 and moving to a world where the Landofile explicitly declares your service version.

Does that makes sense @tvlooy?

**Comment by pirog** [comment]
for additional context we are going to release a new `php` service built on the new Lando 4 service api within the next few months and this should make "default version management"  a thing of the past.

**Comment by tvlooy** [comment]
Oh, yes that does make sense. Great to hear there's a new php service on the way. Where can I get a notification if this is released? We have quite a few developers that use Lando, and I think they would be happy to try it out

**Comment by reynoldsalec** [comment]
I'd watch this repo via GitHub (should notify you on releases) and for more general Lando v4 updates, sign-up to the newsletter (see signup at the bottom of the docs homepage: https://docs.lando.dev).

Also doesn't hurt to be on the Lando Slack; you can always ask questions there, especially on the #contributors channel: https://www.launchpass.com/devwithlando

Going to close this out for now, but thanks for taking the time to contribute!

**Pull request closed without merging**
