### PR TITLE
Define 8.1 as default and 7.3 + 7.4 as legacy

### PR DESCRIPTION
**Pull request by rabauss**
see: https://www.php.net/supported-versions.php

### CODE REVIEW

**Comment by reynoldsalec** [comment]
@pirog doesn't the `legacy` categorization report to the user each time the app is spun up that the version is legacy?

Had some memory that there was a reason we sometimes don't mark a version as legacy right away, but maybe I'm just remembering wrong :)

**Comment by pirog** [comment]
@reynoldsalec originally the purpose of "legacy" was just to denote that the version was EOL. i don't think we are going to continue doing this in the V4 runtime, or, at least it will end up someplace else. 

not against merging this in though since we should provide a reasonable window of continuing to update the v3 stuff.

**Comment by rabauss** [comment]
PHP 7 is end of life so users should keep that in mind. I'd like to have the prominent hint about the legacy version!

**Comment by pirog** [comment]
@rabauss to clarify, we aren't going to present a warning like we currently do, instead in V4 the services "legacy" status will be reported along other status checks, likely after an app start or when running a new `lando status` command

**Pull request closed without merging**
