### PR TITLE
 Update Composer to LTS version 2.2

### PR DESCRIPTION
**Pull request by gitressa**
See [#3029](https://github.com/lando/lando/issues/3029).

I am not sure how to test this locally ... @labboy0276 graciously helped me figure out how to test a Lando plugin with [these steps](https://github.com/lando/drupal/pull/3/#issuecomment-1026116341) but since this is a "step above" another technique is probably needed. Any help would be appreciated.

Maybe I need to do something like this? https://docs.lando.dev/contrib/contrib-building.html

### CODE REVIEW

**Comment by labboy0276** [comment]
Closing in favor of https://github.com/lando/php/pull/25 so tests can run

**Comment by reynoldsalec** [comment]
@gitressa yes! You'd want to clone the PHP plugin into `~/.lando/plugins/@lando/php`, run a `yarn install` within the newly cloned plugin directory, and then run a `lando --clear`. You can then see if you're running the correct php plugin by checking the path by running `lando config --path plugins`.

**Comment by gitressa** [comment]
Thanks @reynoldsalec! I tried this, but still get Composer `2.0.7`:

```
$ mkdir -p ~/.lando/plugins/@lando
$ cd ~/.lando/plugins/@lando
$ git clone https://github.com/lando/php
$ yarn install
$ lando --clear
$ lando config --path plugins | grep php
  { dir: '/home/username/.lando/plugins/@lando/php',
    name: '@lando/php',
    path: '/home/username/.lando/plugins/@lando/php/index.js',
    services: '/home/username/.lando/plugins/@lando/php/services' } ]
```

Create and start Lando with PHP 8.1
```
$ lando init --recipe lamp --name lamp --source cwd --webroot . --option php='8.1'
$ lando start
```

Check versions
```
$ lando info | grep version # first is PHP
    version: '8.1',
    version: '5.7',

$ lando composer --version | grep version
Composer version 2.0.7 2020-11-13 17:31:06
```

**Comment by labboy0276** [comment]
@gitressa the images were not probably not the latest yet.  I would try a rebuild and see if it is there, or purging the images and seeing.

**Comment by gitressa** [comment]
Thanks for chiming in @labboy0276. I cleaned up everything, but still get Composer `2.0.7` ...

- List all containers (even the ones that are not running) `docker ps --all`
- Kill all running containers `docker kill $(docker ps -q)`
- Delete all stopped containers `docker rm $(docker ps -a -q)`
- Delete all images `docker rmi $(docker images -q)`

From [Cleaning up Lando containers](https://colorfield.be/blog/cleaning-lando-containers).

**Comment by labboy0276** [comment]
@gitressa I tried this on a d9 recipe:

```
john@tandem:~/.lando/plugins/@lando$ lando config --path plugins | grep php
  { dir: '/home/john/.lando/plugins/@lando/php',
    name: '@lando/php',
    path: '/home/john/.lando/plugins/@lando/php/index.js',
    services: '/home/john/.lando/plugins/@lando/php/services' },
```

Here is my lando file:

```
name: lando-rando
recipe: drupal9
config:
  php: '8.1'
  via: nginx
```

And the ouput:

```
john@tandem:~/lando/1-test-sites/rando-tests$ lando php -v
PHP 8.1.3 (cli) (built: Feb 18 2022 19:37:16) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.3, Copyright (c), by Zend Technologies
john@tandem:~/lando/1-test-sites/rando-tests$ lando composer --version | grep version
Composer version 2.2.6 2022-02-04 17:00:38
```

Let me try your example now as well

**Comment by labboy0276** [comment]
@gitressa same deal:

```
name: lando-rando
recipe: lamp
config:
  php: '8.1'
  webroot: .
```

```
john@tandem:~/lando/1-test-sites/rando-tests$ lando php -v
PHP 8.1.3 (cli) (built: Feb 18 2022 19:32:26) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.3, Copyright (c), by Zend Technologies
john@tandem:~/lando/1-test-sites/rando-tests$ lando composer --version | grep version
Composer version 2.2.6 2022-02-04 17:00:38
```

I would make sure you are running lando from source when doing these tests.

**Comment by gitressa** [comment]
Thanks @labboy0276, [building Lando from source](https://docs.lando.dev/getting-started/installation.html#from-source) was the missing piece of the puzzle, and I now get Composer `2.2.6`:

```
$ lando.dev composer --version
Composer version 2.2.6 2022-02-04 17:00:38
```

**Comment by reynoldsalec** [comment]
Ah ha, sorry @gitressa, I didn't think about running Lando from source.

I think if you want to run Lando from the most current binary, you could use the custom installation instructions as an alternative: https://docs.lando.dev/php/#custom-installation

In the future once Hyperdrive is updated, it should make it easy to install/specify versions of plugins.

**Comment by gitressa** [comment]
No problem @reynoldsalec, and thanks for the tip about custom installation of PHP plugins. Hyperdrive looks pretty cool and a lot simpler, I am looking forward to trying it :)

**Pull request closed without merging**
